version: '3'
services:
  base:
    image: sleavely/node-awscli:18.x
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
  install:
    extends:
      service: base
    command: npm install
  compile:
    extends:
      service: base
    command: npm run compile
  pre-commit:
    extends:
      service: base
    command: npm run pre:commit
  pre-deploy:
    extends:
      service: base
    command: >
      bash -c "npm run pre:deploy
      && aws cloudformation package --template-file aws/cloudformation/template.yaml --output-template-file packaged.yaml --s3-bucket gotron-cf-midway-ap-southeast-1"
  fix:
    extends:
      service: base
    command: npm run fix
