CREATE OR REPLACE VIEW v_creation_explore AS
select l.id,
    'lyrics' as type,
    l.user_id,
    l.name,
    l.description,
    l.theme,
    l.genre,
    l.language,
    l.caption,
    l.cover_file_uri,
    null as file_uri,
    null as tab_file_uri,
    l.lyrics_text,
    l.project_id,
    l.inspired_id,
    l.created_at,
    l.updated_at,
    l.username,
    l.project_status,
    l.project_started_at,
    l.project_created_at,
    l.project_updated_at
from v_lyrics_explore l
union all
select t.id,
    'track' as type,
    t.user_id,
    t.name,
    t.description,
    t.theme,
    t.genre,
    t.language,
    t.caption,
    t.cover_file_uri,
    t.file_uri,
    t.tab_file_uri,
    null as lyrics_text,
    t.project_id,
    t.inspired_id,
    t.created_at,
    t.updated_at,
    t.username,
    t.project_status,
    t.project_started_at,
    t.project_created_at,
    t.project_updated_at
from v_track_explore t
union all
select s.id,
    'song' as type,
    null as user_id,
    s.name,
    s.description,
    s.theme,
    s.genre,
    s.language,
    s.caption,
    s.cover_file_uri,
    s.track_file_uri as file_uri,
    s.tab_file_uri,
    s.lyrics_text,
    s.id as project_id,
    null as inspired_id,
    s.created_at,
    s.updated_at,
    null as username,
    s.status as project_status,
    s.started_at as project_started_at,
    s.created_at as project_created_at,
    s.updated_at as project_updated_at
from v_song_explore s;