CREATE TABLE IF NOT EXISTS comment (
	id VARCHAR(36) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	creation_id VARCHAR(36) NOT NULL,
	comment VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id ASC),
	FOREIGN KEY (user_id) REFERENCES user(id)
);