CREATE TABLE IF NOT EXISTS info (
	id VARCHAR(36) NOT NULL,
	name VARCHAR(255) NULL,
	description VARCHAR(255) NULL,
	theme VARCHAR(255) NULL,
	genre VARCHAR(255) NULL,
	language VARCHAR(255) NULL,
	cover_file_uri VARCHAR(255) NULL,
	created_at TIMESTAMP NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id ASC)
);