CREATE TABLE project (
	id VARCHAR(36) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	theme VARCHAR(255) NOT NULL,
	genre VARCHAR(255) NOT NULL,
	language VARCHAR(255) NOT NULL,
	caption VARCHAR(255) NOT NULL,
	cover_file_uri VARCHAR(255),
	created_at TIMESTAMP NULL,
	updated_at TIMESTAMP NULL,
	last_viewed_at TIMESTAMP NULL,
	PRIMARY KEY (id ASC)
);