source db/table/info.sql
source db/table/project.sql
source db/table/project_history.sql
source db/table/user.sql
source db/table/lyrics.sql
source db/table/lyrics_history.sql
source db/table/track.sql
source db/table/track_history.sql
source db/table/project_user.sql
source db/view/v_track.sql
source db/view/v_lyrics.sql
source db/view/v_song.sql
source db/view/v_creation.sql
source db/view/v_track_explore.sql
source db/view/v_lyrics_explore.sql
source db/view/v_song_explore.sql
source db/view/v_creation_explore.sql